# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_n', models.CharField(max_length=38)),
                ('l_n', models.CharField(max_length=38)),
                ('eml', models.CharField(max_length=38)),
                ('pw', models.CharField(max_length=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
