# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20171208_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='user',
        ),
        migrations.AddField(
            model_name='container',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_containers', to='first_app.User'),
        ),
    ]
