# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170531_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='h_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
