# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20171210_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='name',
        ),
        migrations.AddField(
            model_name='checklist',
            name='holder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='taked_lists', to='first_app.User'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
